# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Simon Schellaert
description: Passionate computer scientist who loves tackling hard problems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

contact_options:
  - name: Twitter
    icon: fab fa-twitter
    link: https://twitter.com/simonschellaert
  - name: GitHub
    icon: fab fa-github
    link: https://github.com/simonschellaert
  - name: LinkedIn
    icon: fab fa-linkedin
    link: https://www.linkedin.com/in/simonschellaert/
  - name: Email
    icon: fas fa-envelope-square
    link: mailto:me@simonschellaert.com

projects:
  - id: radiobelgium
    name: Radio Belgium
    description: |
      I designed, developed and brought to market [Radio Belgium](https://radiobelgium.be), a native app to turn any iOS or Android device instantly into an amazing radio player.  

      Since launch, the app has been downloaded over 500 000 times with more than __150 000 monthly active users__ and frequently tops the App Store charts. The app was also featured on popular press sites, such as De Standaard and Humo.

      Besides being an interesting project to sharpen my technical skills, it also allowed me to gain __hands-on experience__ in a variety of non-technical fields such as product management, business development and marketing
    action_title: Visit website
    action_link: https://radiobelgium.be
  - id: tapaway
    name: Tapaway
    description: |
      Inspired by the succes of Angry Birds and Cut The Rope, I developed and released my own __physics-based puzzle game__ during high school.

      Tapaway was my first foray into iOS development and made use of the [Cocos2d](https://cocos2d-x.org) game engine, which I integrated with the [Box2D](https://box2d.org/) physic engine.
      This combination allowed me too learn the ropes of __programming and memory management in Objective-C++__.

      The end result was an enjoyable game with over 30 handcrafted levels and received great reviews from numerous players.
      Since this was mainly a learning project, I stopped supporting it when iOS transitioned to 64-bit.
      A video of the gameplay is still available on YouTube.
    action_title: Watch demo on YouTube
    action_link: https://www.youtube.com/watch?v=nZdtnwRD3Bk
  - id: thesis
    name: Master's thesis on Deep Learning
    action_title: Read the paper
    action_link: img/projects/thesis/paper.pdf
    description: |
      After completing courses on __machine learning__, I was excited by its huge potential and decided do my master's thesis in this domain.

      Specifically, my master's thesis is titled __automatic comic colorization and restoration through deep learning__.
      It is about automatically colorizing degraded black-and-white pages from old comics.
      To do so, I built upon recent advances in deep learning and generative adversarial networks.
      Specifically, I proposed a modified network architecture and loss function that leads to more natural results.

      Completing this thesis allowed me to immerse myself into recent deep learning research.
      I also gained a lot of hands-on experience with applying __state-of-the-art deep learning techniques__ to solve challenging problems.
      You can find my full thesis [here](https://libstore.ugent.be/fulltxt/RUG01/002/787/402/RUG01-002787402_2019_0001_AC.pdf) or read the paper below.
  - id: 8-bit
    name: 8-bit computer
    has_video: true
    description: |
      Due to the various lockdowns in 2020, I had a bit more time on my hands than usual.

      One thing that kept me busy was __building a programmable 8-bit computer from logic gates__, based on Ben Eater's [video series](https://eater.net/8bit).
      That series is one of the best explanations of computing and digital electronics I've ever seen.
      Besides, there is something magical about stripping a bunch of wires and turning those into a machine that seems to think.

      In the video, you can see my build generating the __Fibonacci sequence__ (on the 7-segment display in the lower right) at a modest 1 KHz.
      It's the result of many evenings spent behind an oscilloscope, debugging various software and hardware issues.
      But it has been incredibly fun and educational, and it made me appreciate the tech we have now even more..
      I'm currently working on a GPU component to drive a [small OLED display](https://www.adafruit.com/product/326).

  - id: raytracer
    name: Path Tracer in Rust
    description: |
      After completing [Advent of Code](https://adventofcode.com/) in [Rust](https://www.rust-lang.org/) and really liking the programming experience and safety guarantees of the language, I set out to complete a larger project to further __improve my Rust-skills__.

      Writing a path tracer is a great way to become more acquainted with a language, since it touches upon so __many different common aspects of a language__.
      Besides, it is very cool to watch your own program making a scene come alive.

      I'm still working on some key features and plan on publishing the __full source code on GitHub__ in the near future.

# Build settings
markdown: kramdown
sass:
  sass_dir: css

include:
  - _redirects

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
