# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Simon Schellaert
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

contact_options:
  - name: Twitter
    icon: fab fa-twitter
    link: https://twitter.com/simonschellaert
  - name: GitHub
    icon: fab fa-github
    link: https://github.com/simonschellaert
  - name: LinkedIn
    icon: fab fa-linkedin
    link: https://www.linkedin.com/in/simonschellaert/
  - name: Email
    icon: fas fa-envelope-square
    link: mailto:me@simonschellaert.com

projects:
  - id: radiobelgium
    name: Radio Belgium
    description: |
      I designed, developed and brought to market [Radio Belgium](https://radiobelgium.be), a native app to turn any iOS or Android device instantly into an amazing radio player.  

      Since launch, the app has been downloaded over 500 000 times with more than <strong>150 000 monthly active users</strong> and frequently tops the App Store charts. The app was also featured on popular press sites, such as De Standaard and Humo.  

      Besides being an interesting project to sharpen my technical skills, it also allowed me to gain <strong>hands-on experience</strong> in a variety of non-technical fields such as product management, business development and marketing
    action_title: Visit website
    action_link: https://radiobelgium.be
  - id: tapaway
    name: Tapaway
    action_title: Watch demo on YouTube
    action_link: https://www.youtube.com/watch?v=nZdtnwRD3Bk
  - id: raytracer
    name: Ray Tracer in Rust

     

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  sass_dir: css

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
